2022 01 02 C++ updates
tormach/hal_ros_control pull request #8
Opened 2022-01-02 23:06 UTC by zultron

This PR is based on & follows #7, and is second in a series of four to the first version working under ROS2.

PR #6 was the first, buildable but non-working port of the C++ code.  In the process of getting that code to run for the first time, I naturally ran into quite a number of problems, fixed here.

TL;DR:  The nitty-gritty details of the fixes are detailed below.  The first addresses a design problem in the earlier PR.  The rest describe issues encountered while integrating the ROS2 node, controller manager and hardware interface into a HAL real time component, whose launch and execution environment have a few important differences compared to those of the typical ROS2 node.

It turned out that the `ros2_control` distro's hardware interface handle classes can't be subclassed because they don't add `virtual` specifiers on the member functions.  The hardware interface handle subclass from #6 is removed & functionality moved back to the system interface class, and adopts the more traditional (& slightly less efficient) pattern of copying values in and out of interface handles in the `read()` and `write()` functions.

Machinekit HAL realtime components are basically plugins loaded by the setuid `rtapi_app` executable.  They expose (at least) three basic functions: `rtapi_app_main()` init and `rtapi_app_exit()` shutdown functions, and the `funct()` real-time update function.  These characteristics presented a number of challenges integrating into a `ros2_control` controller node and system interface.

For security reasons, setuid executables ignore `$LD_LIBRARY_PATH`.  The ROS 1 version can work around this by adding `/opt/ros/${ROS_DISTRO}/lib` to `ld.so.conf`.  However, it appears that ROS2 `rcl` searches through `$LD_LIBRARY_PATH` on its own to find `librmw_fastrtps_cpp.so` and related libs.  The workaround is to reconstruct `$LD_LIBRARY_PATH` in `rtapi_app_main()`.

Another issue stemming from setuid is fixed in the next PR (where launch files are updated):  FastDDS uses shm-based discovery by default, and files written by the setuid node in `/dev/shm` can't be read by other nodes.  The workaround is to configure UDP discovery for the setuid node; see https://github.com/eProsima/Fast-DDS/issues/1750

The `ros2_control` controller manager node normally(?) runs from the provided `ros2_control_node` executable, where the controller manager `read()`, `update()`, `write()` periodic update functions are run in a separate thread, and the main function blocks on the node's `spin()` function.  In Machinekit HAL, to run in the realtime context, the controller manager node must run from a HAL component plugin.  In the HAL component `rtapi_app_main()` init function, the `spin()` function is instead run in a separate thread, and the periodic update functions are run from the HAL component function, run from a HAL realtime thread.  This wasn't a big challenge, but it does invert the usual pattern, and may be related to ros-controls/ros2_control#330.

Another minor challenge related to loading the controller manager node from a plugin is how to pass it parameter files.  From a command line executable, initializing the ROS context is natural with `rclpp::init(argc, argv)`.  HAL components do accept an array of arguments, and `(argc, argv)` can be synthesized from those.  In the next PR, parameters will be plumbed through the launch files to the `hal_mgr` node, which will pass its arguments to the HAL component.  This scheme feels a little bit dirty, since `hal_mgr` and controller manager share the same arguments, and ROS context init assumes that nodes are all executables.  However, it works fine this way.

One more related challenge is in `ros2_control`, the hardware interface is now loaded from a plugin, and no longer visible to the code running the controller manager node.  The Machinekit HAL component must set up the controller manager from its `rtapi_app_main()` init function, from where it exports the HAL component's update `funct()` that calls the controller manager's `read()`, `update()`, `write()` periodic update functions (the exported function is later added to and run from a real time thread from the HAL config).  The HAL component also needs to set up its HAL pins in the `rtapi_app_main()` init function, but the `hardware_interface::InterfaceInfo` object, which describes the hardware interfaces that will be connected to the HAL pins, is only passed to the hardware system interface plugin.  So even though a HAL component is typically a monolithic plugin in itself, the `ros2_control` system interface must still be loaded as a second plugin, and then because the controller node and system interface have no direct sharing (even via ROS params, IIUC), the system interface must initialize pins for the HAL component initialized in the control node initialization context.  The routines that create HAL pins need the component's `int` ID.  For the system interface to get this ID, the HAL component name is hard-coded into a common header file (this may change), and the system interface must include normally private HAL headers that expose routines to find a component object from its name.  (That then caused clang warnings that broke CI, and my fixes are in a temporary package repository until they and other issues upstream can be resolved.)

2022-01-13 22:18 UTC, zultron commented
Now that #7 is merged (thanks, @facontidavide !), this one is rebased onto that to clearly delineate the changes in the GH interface "commits" etc. tabs.

Draft status removed.  CI tests passing.  Ready for review!

2022-01-18 18:20 UTC, facontidavide requested changes

2022-01-18 18:20 UTC, facontidavide commented on hal_hw_interface/include/hal_hw_interface/hal_system_interface.hpp
> +  std::vector<double>::size_type handle_storage;
`std::vector<double>::size_type ` == `size_t`

Prefer the latter for simplicity.

If I understand correctly, this provides the index to the `storage_`.

Why don't we store the double here, instead of an external vector?

2022-01-18 18:20 UTC, facontidavide commented on hal_hw_interface/include/hal_hw_interface/hal_system_interface.hpp
> +  hal_float_t** alloc_and_init_hal_pin(std::string /*joint_name*/,
usually I prefer passing string by const&, but I understand it is not a big deal here, since this is done only once.

2022-01-21 05:09 UTC, zultron commented on hal_hw_interface/include/hal_hw_interface/hal_system_interface.hpp
> +  std::vector<double>::size_type handle_storage;
See 5c719da for the `size_t` suggestion.

See b6722ac for moving storage directly to the `struct`.  I had no good reason for this, other than the `storage_` vector was an artifact of the ROS1 implementation.

2022-01-21 05:10 UTC, zultron commented on hal_hw_interface/include/hal_hw_interface/hal_system_interface.hpp
> +  hal_float_t** alloc_and_init_hal_pin(std::string /*joint_name*/,
See e5e4427 for added `const` specifiers.

2022-01-21 05:11 UTC, zultron commented
Thanks once again for the review, @facontidavide !  I've addressed each of your suggestions.  All checks are passing.

2022-01-28 12:28 UTC, facontidavide approved these changes

2022-02-01 02:05 UTC, merged